services:

  tamagotchi:
    build: ./
    networks:
      - internal_network

  keycloak-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./keycloak/data/:/var/lib/postgresql/data
    networks:
      - internal_network

  keycloak:
    image: keycloak/keycloak:latest
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD:  ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: ["start-dev"]
    depends_on:
      - keycloak-db
    networks:
      - internal_network

  webserver:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/:ro
    ports:
      - "443:443"
    depends_on:
      - keycloak
      - tamagotchi
    networks:
      - internal_network
      
networks:
  internal_network:
      driver: bridge